services:
  - type: web
    name: mern-role-dashboard-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://mern-intern-gamma.vercel.app
      - key: BACKEND_URL
        value: https://mern-intern-1.onrender.com